apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nw4w0owwn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nw4w0owwn-nodejs 
  name: nw4w0owwn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nw4w0owwn-nodejs 
